# Generated by Django 3.2.8 on 2022-03-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220313_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_use',
            field=models.BooleanField(default=False, verbose_name='是否可用'),
        ),
    ]
