# Generated by Django 3.2.8 on 2022-03-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_alter_guardian_user'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=1, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('guardian', 'name')},
        ),
    ]
